joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000
joint_position_controller: # https://answers.ros.org/question/331384/building-a-custom-hardware-interface-for-moveit/
  type: position_controllers/JointPositionController
  joint: lbr_joint_1
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7
follow_joint_trajectory: # https://ros-planning.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html
  type: position_controllers/JointTrajectoryController
  joints:
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7
  gains:
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
    lbr_joint_1: {p: 10, d: 1, i: 1, i_clamp: 1}
joint_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr_joint_1
  pid: {p: 0.75, i: 0.5, d: 0.01}

