# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200 

# Position controllers
PositionJointInterface_A1_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_1

PositionJointInterface_A2_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_2
  
PositionJointInterface_A3_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_3
  
PositionJointInterface_A4_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_4
  
PositionJointInterface_A5_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_5
  
PositionJointInterface_A6_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_6
  
PositionJointInterface_A7_controller:
  type: position_controllers/JointPositionController
  joint: lbr_joint_7

PositionJointInterface_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  200           # Override default
  action_monitor_rate: 200           # Override default
  stop_trajectory_duration: 0        # Override default

# Velocity controllers
VelocityJointInterface_A1_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_1

VelocityJointInterface_A2_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_2
  
VelocityJointInterface_A3_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_3
  
VelocityJointInterface_A4_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_4
  
VelocityJointInterface_A5_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_5
  
VelocityJointInterface_A6_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_6
  
VelocityJointInterface_A7_controller:
  type: velocity_controllers/JointVelocityController
  joint: lbr_joint_7

VelocityJointInterface_trajectory_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
    - lbr_joint_1
    - lbr_joint_2
    - lbr_joint_3
    - lbr_joint_4
    - lbr_joint_5
    - lbr_joint_6
    - lbr_joint_7

  gains:
    lbr_joint_1: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_5: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_6: {p: 100,  d: 1, i: 1, i_clamp: 30}
    lbr_joint_7: {p: 100,  d: 1, i: 1, i_clamp: 30}

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  200           # Override default
  action_monitor_rate: 200           # Override default
  stop_trajectory_duration: 0        # Override default

